# Linter rule set configuration
# See https://linkml.io/linkml/schemas/linter.html for all rules

# enable the recommended set of rules
extends: recommended
rules:
  # For now I like some to be custom, and I found no easy way
  # to allow only for some exclusions without overloading the
  # entire regex
  standard_naming:
    level: disabled
#  no_empty_title:
#    level: error
