#!/usr/bin/env python3
import sys
from ruamel.yaml import YAML

if len(sys.argv) < 2:
    print("Usage: format_yaml.py <input_file> [output_file]")
    sys.exit(1)

input_file = sys.argv[1]
output_file = sys.argv[2] if len(sys.argv) > 2 else None

yaml = YAML()
yaml.preserve_quotes = True
yaml.indent(mapping=2, sequence=4, offset=2)
yaml.width = 4096  # Prevent line wrapping

with open(input_file, "r") as f:
    data = yaml.load(f)

if output_file:
    with open(output_file, "w") as f:
        yaml.dump(data, f)
else:
    yaml.dump(data, sys.stdout)
